import swaggerAutogen from "swagger-autogen"

const outputFile = "./swagger_output.json" // Output JSON file
const endpointsFiles = ["../routes/*.js"] // Path to your API endpoint files

const doc = {
  info: {
    title: "Your Express API",
    description: "Documentation automatically generated by Swagger Autogen",
  },
  host: "localhost:3000", // Your API host
  basePath: "/", // Base path
  schemes: ["http", "https"], // Available schemes
  consumes: ["application/json"],
  produces: ["application/json"],
}

swaggerAutogen()(outputFile, endpointsFiles, doc)
  .then(() => {
    console.log("Swagger documentation generated successfully")
  })
  .catch((err) => {
    console.error("Error generating Swagger documentation:", err)
  })
